### ISSUE TITLE
Issue from node modules

### ISSUE THREAD

**Issue by KRISHNA-git11** [Elijah-trillionz/discord-bot-buddy#2]
![Screenshot from 2021-11-04 13-05-19](https://user-images.githubusercontent.com/79888512/140304508-b10a3066-f370-4d60-9501-7de0c2efc889.png)
This is the error I get.

**Comment by Elijah-trillionz** [comment]
This is a syntax error. You need to check your code very well for any wrong use of syntax.

But from what I see though, it's like the error is not coming from your code. It seems it is from discord.

Check your node version, if it's not up to 16.6.0, then update it; because discord clearly [states that nodejs must be 16.6.0 or newer](https://www.npmjs.com/package/discord.js).

**Comment by KRISHNA-git11** [comment]
Got it! Thank you
